# AppSpec file for AWS CodeDeploy ECS Blue/Green deployments
# This file defines the deployment configuration for the AI Photobooth application

version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "backend-container"
          ContainerPort: 3000
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - "subnet-placeholder1"
              - "subnet-placeholder2"
            SecurityGroups:
              - "sg-placeholder"
            AssignPublicIp: "DISABLED"

Hooks:
  # Pre-traffic hook - runs before traffic is shifted to new tasks
  BeforeInstall:
    - Location: "scripts/pre-traffic-hook.sh"
      Timeout: 300
      RunAs: root
  
  # Application start hook - runs after new tasks are started but before traffic shift
  ApplicationStart:
    - Location: "scripts/application-start-hook.sh"
      Timeout: 300
      RunAs: root
  
  # Application stop hook - runs before old tasks are terminated
  ApplicationStop:
    - Location: "scripts/application-stop-hook.sh"
      Timeout: 300
      RunAs: root
  
  # Validation hook - runs after traffic is shifted to validate deployment
  ValidateService:
    - Location: "scripts/validate-service-hook.sh"
      Timeout: 600
      RunAs: root